version: '3.3'
services:
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    logging:
      driver: none
    depends_on:
      - mysql
    links:
      - mysql:db
    expose:
      - "9999"
    ports:
      - "9999:80"
  jaegertracing:
    image: jaegertracing/all-in-one:latest
    logging:
      driver: none
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  eastergift:
    image: quarkus/easter-gift
    expose:
      - "8080"
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      quarkus_datasource_url: "jdbc:mariadb://mysql:3306/db?verifyServerCertificate=false&useSSL=false"
volumes:
  my-db:
